spring:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
  jpa:
    database: h2
    database-platform : org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  servlet:
    encoding:
      force-response: true
